name: Publish snapshot

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  publish-snapshot:
    runs-on: macos-14
    if: github.repository == 'IlyaGulya/anvil-utils'
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v2
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          check-latest: true

      - name: Publish Release
        run: ./gradlew clean publish --no-build-cache --no-daemon --stacktrace
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
